In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("books.csv")

In [3]:
data=data[data.columns.drop(["isbn","isbn13","image_url","small_image_url"])]
print(data.info())
print("*"*60)
print(data.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1354 entries, 0 to 1353
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   book_id                    1354 non-null   int64
 1   goodreads_book_id          1354 non-null   int64
 2   best_book_id               1354 non-null   int64
 3   work_id                    1354 non-null   int64
 4   books_count                1354 non-null   int64
 5   authors                    1354 non-null   object
 6   original_publication_year  1351 non-null   float64
 7   original_title             1302 non-null   object
 8   title                      1354 non-null   object
 9   language_code              1245 non-null   object
 10  average_rating             1354 non-null   float64
 11  ratings_count              1354 non-null   int64
 12  work_ratings_count         1354 non-null   int64
 13  work_text_reviews_count    1354 non-null   int64
 14  ratings_1                  1354 non-null   int64
 15  ratings_2                  1354 non-null   int64
 16  ratings_3                  1354 non-null   int64
 17  ratings_4                  1354 non-null   int64
 18  ratings_5                  1354 non-null   int64
dtypes: float64(2), int64(13), object(4)
memory usage: 201.1+ KB
None
************************************************************
book_id                        0
goodreads_book_id              0
best_book_id                   0
work_id                        0
books_count                    0
authors                        0
original_publication_year      3
original_title                52
title                          0
language_code                109
average_rating                 0
ratings_count                  0
work_ratings_count             0
work_text_reviews_count        0
ratings_1                      0
ratings_2                      0
ratings_3                      0
ratings_4                      0
ratings_5                      0
dtype: int64

In [5]:
data_without_nullrows=data.dropna()
print(data.shape)
print(data_without_nullrows.shape)

(1354, 19)
(1197, 19)

In [6]:
Harry_with_nulls=data[data["title"].str.contains("Harry Potter",case=False)]
Harry_with_nulls

,book_id,goodreads_book_id,best_book_id,work_id,books_count,authors,original_publication_year,original_title,title,language_code,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5
1,2,3,3,4640799,491,"J.K. Rowling, Mary GrandPré",1997.0,Harry Potter and the Philosopher's Stone,Harry Potter and the Sorcerer's Stone (Harry P...,eng,4.44,4602479,4800065,75867,75504,101676,455024,1156318,3011543
6,18,5,5,2402163,376,"J.K. Rowling, Mary GrandPré, Rufus Beck",1999.0,Harry Potter and the Prisoner of Azkaban,Harry Potter and the Prisoner of Azkaban (Harr...,eng,4.53,1832823,1969375,36099,6716,20413,166129,509447,1266670
8,21,2,2,2809203,307,"J.K. Rowling, Mary GrandPré",2003.0,Harry Potter and the Order of the Phoenix,Harry Potter and the Order of the Phoenix (Har...,eng,4.46,1735368,1840548,28685,9528,31577,180210,494427,1124806
9,23,15881,15881,6231171,398,"J.K. Rowling, Mary GrandPré",1998.0,Harry Potter and the Chamber of Secrets,Harry Potter and the Chamber of Secrets (Harry...,eng,4.37,1779331,1906199,34172,8253,42251,242345,548266,1065084
10,24,6,6,3046572,332,"J.K. Rowling, Mary GrandPré",2000.0,Harry Potter and the Goblet of Fire,Harry Potter and the Goblet of Fire (Harry Pot...,eng,4.53,1753043,1868642,31084,6676,20210,151785,494926,1195045
11,25,136251,136251,2963218,263,"J.K. Rowling, Mary GrandPré",2007.0,Harry Potter and the Deathly Hallows,Harry Potter and the Deathly Hallows (Harry Po...,eng,4.61,1746574,1847395,51942,9363,22245,113646,383914,1318227
12,27,1,1,41335427,275,"J.K. Rowling, Mary GrandPré",2005.0,Harry Potter and the Half-Blood Prince,Harry Potter and the Half-Blood Prince (Harry ...,eng,4.54,1678823,1785676,27520,7308,21516,136333,459028,1161491
96,422,862041,862041,2962492,76,J.K. Rowling,1998.0,Complete Harry Potter Boxed Set,"Harry Potter Boxset (Harry Potter, #1-7)",eng,4.74,190050,204125,6508,1105,1285,7020,30666,164049
613,3753,10,10,21457570,6,J.K. Rowling,2005.0,"Harry Potter Collection (Harry Potter, #1-6)","Harry Potter Collection (Harry Potter, #1-6)",eng,4.73,24618,26274,882,203,186,946,3891,21048
1036,7018,483445,483445,471792,42,David Colbert,2001.0,The Magical Worlds of Harry Potter: A Treasury...,The Magical Worlds of Harry Potter: A Treasury...,eng,3.96,13820,15145,267,329,1125,3766,3593,6332
1266,9048,2002,2002,8621948,5,J.K. Rowling,2001.0,NaN,Harry Potter Schoolbooks Box Set: Two Classic ...,eng,4.40,10736,11732,185,106,304,1548,2595,7179

In [7]:
Harry_without_nulls=data_without_nullrows[data_without_nullrows["original_title"].str.contains("Harry Potter",case=False)]
Harry_without_nulls

,book_id,goodreads_book_id,best_book_id,work_id,books_count,authors,original_publication_year,original_title,title,language_code,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5
1,2,3,3,4640799,491,"J.K. Rowling, Mary GrandPré",1997.0,Harry Potter and the Philosopher's Stone,Harry Potter and the Sorcerer's Stone (Harry P...,eng,4.44,4602479,4800065,75867,75504,101676,455024,1156318,3011543
6,18,5,5,2402163,376,"J.K. Rowling, Mary GrandPré, Rufus Beck",1999.0,Harry Potter and the Prisoner of Azkaban,Harry Potter and the Prisoner of Azkaban (Harr...,eng,4.53,1832823,1969375,36099,6716,20413,166129,509447,1266670
8,21,2,2,2809203,307,"J.K. Rowling, Mary GrandPré",2003.0,Harry Potter and the Order of the Phoenix,Harry Potter and the Order of the Phoenix (Har...,eng,4.46,1735368,1840548,28685,9528,31577,180210,494427,1124806
9,23,15881,15881,6231171,398,"J.K. Rowling, Mary GrandPré",1998.0,Harry Potter and the Chamber of Secrets,Harry Potter and the Chamber of Secrets (Harry...,eng,4.37,1779331,1906199,34172,8253,42251,242345,548266,1065084
10,24,6,6,3046572,332,"J.K. Rowling, Mary GrandPré",2000.0,Harry Potter and the Goblet of Fire,Harry Potter and the Goblet of Fire (Harry Pot...,eng,4.53,1753043,1868642,31084,6676,20210,151785,494926,1195045
11,25,136251,136251,2963218,263,"J.K. Rowling, Mary GrandPré",2007.0,Harry Potter and the Deathly Hallows,Harry Potter and the Deathly Hallows (Harry Po...,eng,4.61,1746574,1847395,51942,9363,22245,113646,383914,1318227
12,27,1,1,41335427,275,"J.K. Rowling, Mary GrandPré",2005.0,Harry Potter and the Half-Blood Prince,Harry Potter and the Half-Blood Prince (Harry ...,eng,4.54,1678823,1785676,27520,7308,21516,136333,459028,1161491
96,422,862041,862041,2962492,76,J.K. Rowling,1998.0,Complete Harry Potter Boxed Set,"Harry Potter Boxset (Harry Potter, #1-7)",eng,4.74,190050,204125,6508,1105,1285,7020,30666,164049
613,3753,10,10,21457570,6,J.K. Rowling,2005.0,"Harry Potter Collection (Harry Potter, #1-6)","Harry Potter Collection (Harry Potter, #1-6)",eng,4.73,24618,26274,882,203,186,946,3891,21048
1036,7018,483445,483445,471792,42,David Colbert,2001.0,The Magical Worlds of Harry Potter: A Treasury...,The Magical Worlds of Harry Potter: A Treasury...,eng,3.96,13820,15145,267,329,1125,3766,3593,6332

In [8]:
Harry_with_nulls.loc[:,["book_id","title","average_rating"]]

,book_id,title,average_rating
1,2,Harry Potter and the Sorcerer's Stone (Harry P...,4.44
6,18,Harry Potter and the Prisoner of Azkaban (Harr...,4.53
8,21,Harry Potter and the Order of the Phoenix (Har...,4.46
9,23,Harry Potter and the Chamber of Secrets (Harry...,4.37
10,24,Harry Potter and the Goblet of Fire (Harry Pot...,4.53
11,25,Harry Potter and the Deathly Hallows (Harry Po...,4.61
12,27,Harry Potter and the Half-Blood Prince (Harry ...,4.54
96,422,"Harry Potter Boxset (Harry Potter, #1-7)",4.74
613,3753,"Harry Potter Collection (Harry Potter, #1-6)",4.73
1036,7018,The Magical Worlds of Harry Potter: A Treasury...,3.96
1266,9048,Harry Potter Schoolbooks Box Set: Two Classic ...,4.40

In [9]:
print(Harry_with_nulls.ratings_count.max())
max_rating=Harry_with_nulls.ratings_count.max()

4602479

In [11]:
max_row=Harry_with_nulls[Harry_with_nulls.ratings_count==max_rating]
max_row

,book_id,goodreads_book_id,best_book_id,work_id,books_count,authors,original_publication_year,original_title,title,language_code,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5
1,2,3,3,4640799,491,"J.K. Rowling, Mary GrandPré",1997.0,Harry Potter and the Philosopher's Stone,Harry Potter and the Sorcerer's Stone (Harry P...,eng,4.44,4602479,4800065,75867,75504,101676,455024,1156318,3011543

In [12]:
best_seller = data[data['ratings_count'] == max_rating]

print(f"The best selling Harry Potter book is: {best_seller['title'].values[0]}")

The best selling Harry Potter book is: Harry Potter and the Sorcerer's Stone (Harry Potter, #1)

In [13]:
average_rating = data['average_rating'].mean()
median_rating = data['average_rating'].median()
print("Average Rating:", average_rating)
print("Median Rating:", median_rating)

Average Rating: 3.999357459379616
Median Rating: 4.0

In [14]:
df = pd.read_csv('books.csv')

hp_books = df[df['authors'].str.contains('J.K. Rowling')]

total_ratings = hp_books['ratings_count'].sum()
average_rating = total_ratings / len(hp_books)

print(f'Average rating of Harry Potter books is {average_rating}')

Average rating of Harry Potter books is 1310798.8333333333